name: RessourceTowers
main: de.prwh.ressourcetowers.main.RTMain
version: 0.0.9
api-version: 1.16
author: Dragonisser
softdepend: [FactionsX]

commands:
    rt:
      description: basic stuff.
      usage: /<command>
      permission: ressourcetowers
      permission-message: You don't have the permissions <permission>