name: RessourceTowers
main: de.prwh.ressourcetowers.main.RTMain
version: 0.0.4

commands:
    addTower:
      description: Adds the tower on your location/coordinates with the given TowerType.
      usage: /<command> [towertype]
      permission: ressourcetowers.addtower
      permission-message: You don't have the permissions <permission>
    listTower:
      description: Lists all towers.
      usage: /<command>
      permission: ressourcetowers.listtower
      permission-message: You don't have the permissions <permission>
    removeTower:
      description: Removes the tower at your location or all.
      permission: ressourcetowers.removetower
      permission-message: You don't have the permissions <permission>
    chunkTower:
      description: Cheks if a tower is in the chunk you are standing.
      usage: /<command>
      permission: ressourcetowers.chunktower
      permission-message: You don't have the permissions <permission>